### ISSUE TITLE
need kotlin update

### ISSUE THREAD

**Issue by juanjoserodrigolazaro** [Aneesh1990/flutter_tinder_card#1]
Hello this project in kotlin is out of date, it needs "1.2.71" but we are on "1.3.50"

**Comment by Aneesh1990** [comment]
will do

**Comment by atul-chaudhary** [comment]
I am facing the same issue, Please resolve this issue ASAP

**Comment by atul-chaudhary** [comment]
error is resolved

**Comment by Gama-Development** [comment]
@atul-chaudhary how did you solve it??
![image](https://user-images.githubusercontent.com/46693149/76689100-4c065680-65f8-11ea-86b7-872dc825caec.png)
I have this error

**Comment by Aneesh1990** [comment]
solved
